export const FETCH_APPLICABLE_ADVISORIES = 'FETCH_APPLICABLE_ADVISORIES';
export const EXPAND_ADVISORY_ROW = 'EXPAND_ADVISORY_ROW';
export const SELECT_ADVISORY_ROW = 'SELECT_ADVISORY_ROW';
export const CHANGE_ADVISORY_LIST_PARAMS = 'CHANGE_ADVISORY_LIST_PARAMS';
export const FETCH_SYSTEMS = 'FETCH_SYSTEMS';
export const CHANGE_SYSTEMS_LIST_PARAMS = 'CHANGE_SYSTEMS_LIST_PARAMS';
export const CHANGE_SYSTEM_ADVISORY_LIST_PARAMS =
    'CHANGE_SYSTEM_SYSTEMS_LIST_PARAMS';
export const EXPAND_SYSTEM_ADVISORY_ROW = 'EXPAND_SYSTEM_ADVISORY_ROW';
export const FETCH_APPLICABLE_SYSTEM_ADVISORIES =
    'FETCH_APPLICABLE_SYSTEM_ADVISORIES';
export const FETCH_SYSTEM_DETAILS = 'FETCH_SYSTEM_DETAILS';
export const SELECT_SYSTEM_ADVISORY_ROW = 'SELECT_SYSTEM_ADVISORY_ROW';
