export const FETCH_APPLICABLE_ADVISORIES = 'FETCH_APPLICABLE_ADVISORIES';
export const EXPAND_ADVISORY_ROW = 'EXPAND_ADVISORY_ROW';
export const SELECT_ADVISORY_ROW = 'SELECT_ADVISORY_ROW';
export const CHANGE_ADVISORY_LIST_PARAMS = 'CHANGE_ADVISORY_LIST_PARAMS';
export const FETCH_SYSTEMS = 'FETCH_SYSTEMS';
