export const FETCH_APPLICABLE_ADVISORIES = 'FETCH_APPLICABLE_ADVISORIES';
export const EXPAND_ADVISORY_ROW = 'EXPAND_ADVISORY_ROW';
export const SELECT_ADVISORY_ROW = 'SELECT_ADVISORY_ROW';
export const CHANGE_ADVISORY_LIST_PARAMS = 'CHANGE_ADVISORY_LIST_PARAMS';
export const CHANGE_SYSTEM_ADVISORY_LIST_PARAMS =
    'CHANGE_SYSTEM_SYSTEMS_LIST_PARAMS';
export const EXPAND_SYSTEM_ADVISORY_ROW = 'EXPAND_SYSTEM_ADVISORY_ROW';
export const FETCH_APPLICABLE_SYSTEM_ADVISORIES =
    'FETCH_APPLICABLE_SYSTEM_ADVISORIES';
export const SELECT_SYSTEM_ADVISORY_ROW = 'SELECT_SYSTEM_ADVISORY_ROW';
export const CLEAR_SYSTEM_ADVISORIES = 'CLEAR_SYSTEM_ADVISORIES';
export const FETCH_ADVISORY_DETAILS = 'FETCH_ADVISORY_DETAILS';
export const CLEAR_ADVISORY_DETAILS = 'CLEAR_ADVISORY_DETAILS';
export const CHANGE_SYSTEM_PACKAGES_LIST_PARAMS =
    'CHANGE_SYSTEM_PACKAGES_LIST_PARAMS';
export const FETCH_APPLICABLE_SYSTEM_PACKAGES =
    'FETCH_APPLICABLE_SYSTEM_PACKAGES';
export const SELECT_SYSTEM_PACKAGES_ROW = 'SELECT_SYSTEM_PACKAGES_ROW';
export const CLEAR_SYSTEM_PACKAGES = 'CLEAR_SYSTEM_PACKAGES';
export const TRIGGER_GLOBAL_FILTER = 'TRIGGER_GLOBAL_FILTER';
export const FETCH_PACKAGES_LIST = 'FETCH_PACKAGES_LIST';
export const FETCH_PACKAGE_DETAILS = 'FETCH_PACKAGE_DETAILS';
export const CLEAR_PACKAGE_DETAILS = 'CLEAR_PACKAGE_DETAILS';
export const CHANGE_PACKAGES_LIST_PARAMS = 'CHANGE_PACKAGES_LIST_PARAMS';
export const FETCH_PACKAGE_SYSTEMS = 'FETCH_PACKAGE_SYSTEMS';
export const CLEAR_PACKAGE_SYSTEMS = 'CLEAR_PACKAGE_SYSTEMS';
export const FETCH_CVES_INFO = 'FETCH_CVES_INFO';
export const CHANGE_CVES_STORE_PARAMS = 'CHANGE_CVES_STORE_PARAMS';
export const FETCH_SYSTEM_DETAIL = 'FETCH_SYSTEM_DETAIL';
export const CLEAR_ENTITIES = 'CLEAR_ENTITIES';
export const CHANGE_ENTITIES_PARAMS = 'CHANGE_ENTITIES_PARAMS';
export const CHANGE_SYSTEMS_PARAMS = 'CHANGE_SYSTEMS_PARAMS';
export const CHANGE_AFFECTED_SYSTEMS_PARAMS = 'CHANGE_AFFECTED_SYSTEMS_PARAMS';
export const CHANGE_PACKAGE_SYSTEMS_PARAMS = 'CHANGE_PACKAGE_SYSTEMS_PARAMS';

export const CLEAR_INVENTORY_REDUCER = 'CLEAR_INVENTORY_REDUCER';
export const CLEAR_PACKAGE_SYSTEMS_REDUCER = 'CLEAR_PACKAGE_SYSTEMS_REDUCER';
export const CLEAR_ADVISORY_SYSTEMS_REDUCER = 'CLEAR_ADVISORY_SYSTEMS_REDUCER';

export const CHANGE_SYSTEMS_METADATA = 'CHANGE_SYSTEMS_METADATA';
export const CHANGE_TAGS = 'CHANGE_TAGS';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const CHANGE_GLOBAL_TAGS = 'CHANGE_GLOBAL_TAGS';
export const CHANGE_WORKLOADS = 'CHANGE_WORKLOADS';
export const CHANGE_SIDS = 'CHANGE_SIDS';

export const FETCH_ALL_PATCH_SETS = 'FETCH_ALL_PATCH_SETS';
export const SELECT_PATCH_SET_ROW = 'SELECT_PATCH_SET_ROW';
export const CHANGE_PATCH_SET_PARAMS = 'CHANGE_PATCH_SET_PARAMS';
