version: '3'

services:
  sonar:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROJECT_NAME="Patchman UI"
      - PROJECT_KEY=insights:patchman-ui
      - SONAR_HOST_URL
      - SONAR_CERT_URL
      - SONAR_LOGIN
    command: /run.sh
    volumes:
      - ../../:/usr/src
    security_opt:
      - label=disable
